### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by rickbase1** [matematik7/rpi-dashboard#1]
hi, I am trying to install your rpi-dashboard on Raspian and hit a build error when trying to set up monkey in dudac.  Here is my complete log for reference.  Any ideas?  I got a build error at the dudac/dudac step that seems to cause the problem later,

Looking fwd to working wit this app and REST for my project.

Thanks

Rick

pi@Symmetry-RPI ~ $ git clone git://git.drogon.net/wiringPi
Cloning into 'wiringPi'...
remote: Counting objects: 742, done.
remote: Compressing objects: 100% (676/676), done.
remote: Total 742 (delta 537), reused 94 (delta 58)
Receiving objects: 100% (742/742), 262.85 KiB | 126 KiB/s, done.
Resolving deltas: 100% (537/537), done.
pi@Symmetry-RPI ~ $ cd wiringPi && ./build
# wiringPi Build script

WiringPi Library
[UnInstall]
[Compile] wiringPi.c
[Compile] wiringSerial.c
[Compile] wiringShift.c
[Compile] piHiPri.c
[Compile] piThread.c
[Compile] wiringPiSPI.c
[Compile] wiringPiI2C.c
[Compile] softPwm.c
[Compile] softTone.c
[Compile] mcp23008.c
[Compile] mcp23016.c
[Compile] mcp23017.c
[Compile] mcp23s08.c
[Compile] mcp23s17.c
[Compile] sr595.c
[Compile] pcf8574.c
[Compile] pcf8591.c
[Compile] mcp3002.c
[Compile] mcp3004.c
[Compile] mcp4802.c
[Compile] max31855.c
[Compile] mcp3422.c
[Compile] max5322.c
[Compile] sn3218.c
[Compile] drcSerial.c
[Compile] wpiExtensions.c
[Link (Dynamic)]
[Install Headers]
[Install Dynamic Lib]

WiringPi Devices Library
[UnInstall]
[Compile] ds1302.c
[Compile] maxdetect.c
[Compile] piNes.c
[Compile] gertboard.c
[Compile] piFace.c
[Compile] lcd128x64.c
[Compile] lcd.c
[Compile] piGlow.c
[Link (Dynamic)]
[Install Headers]
[Install Dynamic Lib]

GPIO Utility
[Compile] gpio.c
[Compile] readall.c
[Compile] pins.c
[Link]
[Install]

All Done.

NOTE: To compile programs with wiringPi, you need to add:
    -lwiringPi
  to your compile line(s) To use the Gertboard, MaxDetect, etc.
  code (the devLib), you need to also add:
    -lwiringPiDev
  to your compile line(s).

pi@Symmetry-RPI ~/wiringPi $ git clone https://github.com/monkey/dudac.git
Cloning into 'dudac'...
remote: Counting objects: 305, done.
remote: Total 305 (delta 0), reused 0 (delta 0), pack-reused 305
Receiving objects: 100% (305/305), 85.35 KiB, done.
Resolving deltas: 100% (177/177), done.
pi@Symmetry-RPI ~/wiringPi $ dudac/dudac -s
Duda Client Manager - v0.31
http://duda.io
http://monkey-project.com

[i] HOME        : /home/pi/.dudac/
[i] STAGE       : /home/pi/.dudac/stage/
[+] Monkey: cloning source code                                            [OK]
[+] Duda: cloning source code                                              [OK]
[+] GIT Monkey  : switch HEAD to 'dst-1'                                   [OK]
[+] GIT Duda    : switch HEAD to 'dst-1'                                   [OK]
[+] GIT Monkey  : archive                                                  [OK]
[+] GIT Duda    : archive                                                  [OK]
[+] Monkey      : prepare build                                            [OK]
[+] Monkey      : building                                                 [OK]
--- Compiler Warnings ---
mk_method.c:121:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
mk_epoll.c:302:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
mk_epoll.c:399:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
--- \* --- \* --- \* --- \* ---

pi@Symmetry-RPI ~/wiringPi $ git clone https://github.com/matematik7/rpi-dashboard.git
Cloning into 'rpi-dashboard'...
error: The requested URL returned error: 403 while accessing https://github.com/matematik7/rpi-dashboard.git/info/refs
fatal: HTTP request failed
pi@Symmetry-RPI ~/wiringPi $ git clone https://github.com/matematik7/rpi-dashboard.git
Cloning into 'rpi-dashboard'...
remote: Counting objects: 1565, done.
remote: Total 1565 (delta 0), reused 0 (delta 0), pack-reused 1565
Receiving objects: 100% (1565/1565), 295.48 KiB | 327 KiB/s, done.
Resolving deltas: 100% (1041/1041), done.
pi@Symmetry-RPI ~/wiringPi $ cd rpi-dashboard &&git checkout tags/v0.2.0
Note: checking out 'tags/v0.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 86419c4... Docs: Updated version on release of v0.2.0.
pi@Symmetry-RPI ~/wiringPi/rpi-dashboard $ dudac/dudac -w rpi-dashboard/src
bash: dudac/dudac: No such file or directory
pi@Symmetry-RPI ~/wiringPi/rpi-dashboard $ dudac/dudac -w rpi-dashboard/src
bash: dudac/dudac: No such file or directory
pi@Symmetry-RPI ~/wiringPi/rpi-dashboard $ cd ..
pi@Symmetry-RPI ~/wiringPi $ dudac/dudac -w rpi-dashboard/src
Duda Client Manager - v0.31
http://duda.io
http://monkey-project.com

[i] HOME        : /home/pi/.dudac/
[i] STAGE       : /home/pi/.dudac/stage/
[+] WebService  : clean                                                    [OK]
[+] WebService  : build                                                    [FAILED]
## [-] Command exit (status=2): make -C /home/pi/wiringPi/rpi-dashboard/src

make: Entering directory '/home/pi/wiringPi/rpi-dashboard/src'
  [CC]   rpi_main.o
  [CC]   rpi_modules.o
  [CC]   rpi_security.o
  [CC]   rpi_config.o
  [CC]   rpi_cpu.o
  [CC]   rpi_network.o
  [CC]   rpi_memory.o
  [CC]   rpi_storage.o
  [CC]   rpi_string.o
  [CC]   rpi_logger.o
  [CC]   rpi_websocket.o
  [CC]   rpi_gpio.o
  [CC]   rpi_i2c.o
  [CC]   rpi_serial.o
  [CC]   rpi_spi.o
  [CC]   rpi_shift.o
rpi_logger.c:27:17: fatal error: rrd.h: No such file or directory
compilation terminated.
  [CC]   rpi_general.o
Makefile:29: recipe for target 'rpi_logger.o' failed
make: **\* [rpi_logger.o] Error 1
make: **\* Waiting for unfinished jobs....
## make: Leaving directory '/home/pi/wiringPi/rpi-dashboard/src'

pi@Symmetry-RPI ~/wiringPi $ cd ..
pi@Symmetry-RPI ~ $ dudac/dudac -w rpi-dashboard/src
bash: dudac/dudac: No such file or directory
pi@Symmetry-RPI ~ $ cd /wiringPi
bash: cd: /wiringPi: No such file or directory
pi@Symmetry-RPI ~ $ cd wiringPi
pi@Symmetry-RPI ~/wiringPi $ dudac/dudac -w rpi-dashboard/src
Duda Client Manager - v0.31
http://duda.io
http://monkey-project.com

[i] HOME        : /home/pi/.dudac/
[i] STAGE       : /home/pi/.dudac/stage/
[+] WebService  : clean                                                    [OK]
[+] WebService  : build                                                    [FAILED]
## [-] Command exit (status=2): make -C /home/pi/wiringPi/rpi-dashboard/src

make: Entering directory '/home/pi/wiringPi/rpi-dashboard/src'
  [CC]   rpi_main.o
  [CC]   rpi_security.o
  [CC]   rpi_modules.o
  [CC]   rpi_config.o
  [CC]   rpi_memory.o
  [CC]   rpi_cpu.o
  [CC]   rpi_network.o
  [CC]   rpi_storage.o
  [CC]   rpi_string.o
  [CC]   rpi_websocket.o
  [CC]   rpi_logger.o
  [CC]   rpi_gpio.o
  [CC]   rpi_i2c.o
  [CC]   rpi_spi.o
  [CC]   rpi_serial.o
  [CC]   rpi_shift.o
rpi_logger.c:27:17: fatal error: rrd.h: No such file or directory
compilation terminated.
  [CC]   rpi_general.o
Makefile:29: recipe for target 'rpi_logger.o' failed
make: **\* [rpi_logger.o] Error 1

**Comment by domenipavec** [comment]
You are missing headers of rrd library, please install librrd-dev. This is noted in installation instructions: http://docs.rpi-dashboard.com/build_from_source/README.html
Please follow them.

**Comment by tech189** [comment]
This website isn't up anymore and isn't in the wayback machine, does anyone know how to build from source?

**Comment by domenipavec** [comment]
@tech189 as specified in README new documentation location is on gitbooks: https://matematik7.gitbooks.io/rpi-dashboard-docs/content/
